---
apiVersion: v1
kind: ConfigMap
metadata:
  name: train-config
data:
  train.yml: |
        projects:
          - 1
          - 3
        approved: True
        note_mr_approved: TRAIN PUSH
        strategy: jobs
        url: https://gitlab.com/
        token: 
        limit: 100
        sort: desc
        order_by: created_at
        state: opened
        rebase: True
        merge: False
        interval: 20
        job_per_req: 200

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: train
  labels:
    app: train
spec:
  replicas: 1
  selector:
    matchLabels:
      app: train
  template:
    metadata:
      labels:
        app: train
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
    spec:
      containers:
      - name: train
        image: train:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "200Mi"
        command: ["/bin/bash", "-c", "python train.py"]
        volumeMounts:
          - name: train-config
            mountPath: "/train/config/"
      volumes:
        - name: train-config
          configMap:
            name: train-config
      nodeSelector:
        kubernetes.io/arch: amd64
        role: infra
